/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package problema_inventario.vistas;

import problema_inventario.models.Probabilistico;

/**
 *
 * @author Slaush
 */
public class RespuestaProb extends javax.swing.JFrame {

    /**
     * Creates new form RespuestaProb
     */
    public RespuestaProb(Probabilistico general, String unidad) 
    {
        super("Análisis de costos de inventario por "+ unidad + " para el modelo Probabilistico");
        initComponents();
        initLabel(unidad);
        this.problema = general;
        this.unidad = unidad;
        
        initResultBasico(general);
         setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        curvaButton2 = new javax.swing.JButton();
        cierraButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        demandaLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mantenimientoLabel = new javax.swing.JLabel();
        leadTimeLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        demandaInput = new javax.swing.JTextField();
        costoInput = new javax.swing.JTextField();
        mantenimientoInput = new javax.swing.JTextField();
        leadTimeInput = new javax.swing.JTextField();
        adquisicionInput = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        intervaloLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        pedidosLabel = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        EOQInput = new javax.swing.JTextField();
        toInput = new javax.swing.JTextField();
        costoEscasezInput = new javax.swing.JTextField();
        costoMantenimientoInput = new javax.swing.JTextField();
        TCUInput = new javax.swing.JTextField();
        nPedidosInput = new javax.swing.JTextField();
        reorderInput = new javax.swing.JTextField();
        escasezMostrarLabel = new javax.swing.JLabel();
        escasezResult = new javax.swing.JTextField();
        desviacionDemandaLabel = new javax.swing.JLabel();
        desvDemandaInput = new javax.swing.JTextField();
        varianzaTimeLabel = new javax.swing.JLabel();
        varianzaTimeInput = new javax.swing.JTextField();
        costoVentaLabel = new javax.swing.JLabel();
        ventaInput = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        nivelSeguridadInput = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Gráficas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto Cn", 0, 18))); // NOI18N

        curvaButton2.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        curvaButton2.setText("Análisis de Costo de Inventario");
        curvaButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                curvaButton2ActionPerformed(evt);
            }
        });

        cierraButton2.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        cierraButton2.setText("Perfil del Inventario");
        cierraButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cierraButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(cierraButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addComponent(curvaButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(curvaButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cierraButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Roboto Cn", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DATOS DE ENTRADA");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        demandaLabel.setBackground(new java.awt.Color(255, 255, 255));
        demandaLabel.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        demandaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        demandaLabel.setText("Demanda");
        demandaLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Costo de orden");
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        mantenimientoLabel.setBackground(new java.awt.Color(255, 255, 255));
        mantenimientoLabel.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        mantenimientoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mantenimientoLabel.setText("Costo de mantenimiento");
        mantenimientoLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        leadTimeLabel.setBackground(new java.awt.Color(255, 255, 255));
        leadTimeLabel.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        leadTimeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leadTimeLabel.setText("Lead Time");
        leadTimeLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Costo de adquisición de la unidad:");
        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel7.setFont(new java.awt.Font("Roboto Cn", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("VALOR");
        jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        demandaInput.setEditable(false);
        demandaInput.setBackground(new java.awt.Color(255, 255, 255));
        demandaInput.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        demandaInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        demandaInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                demandaInputActionPerformed(evt);
            }
        });

        costoInput.setEditable(false);
        costoInput.setBackground(new java.awt.Color(255, 255, 255));
        costoInput.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        costoInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        costoInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costoInputActionPerformed(evt);
            }
        });

        mantenimientoInput.setEditable(false);
        mantenimientoInput.setBackground(new java.awt.Color(255, 255, 255));
        mantenimientoInput.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        mantenimientoInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mantenimientoInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mantenimientoInputActionPerformed(evt);
            }
        });

        leadTimeInput.setEditable(false);
        leadTimeInput.setBackground(new java.awt.Color(255, 255, 255));
        leadTimeInput.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        leadTimeInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        leadTimeInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leadTimeInputActionPerformed(evt);
            }
        });

        adquisicionInput.setEditable(false);
        adquisicionInput.setBackground(new java.awt.Color(255, 255, 255));
        adquisicionInput.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        adquisicionInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        adquisicionInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adquisicionInputActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Roboto Cn", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("ANÁLISIS DEL ORDEN ECONÓMICO");
        jLabel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Cantidad a ordenar");
        jLabel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        intervaloLabel.setBackground(new java.awt.Color(255, 255, 255));
        intervaloLabel.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        intervaloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        intervaloLabel.setText("Intervalo");
        intervaloLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Punto de reorden");
        jLabel12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Costo de escasez");
        jLabel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Costo de mantenimiento");
        jLabel14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Costo total de inventario ");
        jLabel15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        pedidosLabel.setBackground(new java.awt.Color(255, 255, 255));
        pedidosLabel.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        pedidosLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pedidosLabel.setText("Cantidad de Pedidos");
        pedidosLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel19.setFont(new java.awt.Font("Roboto Cn", 1, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("VALOR");
        jLabel19.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        EOQInput.setEditable(false);
        EOQInput.setBackground(new java.awt.Color(255, 255, 255));
        EOQInput.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        EOQInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EOQInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EOQInputActionPerformed(evt);
            }
        });

        toInput.setEditable(false);
        toInput.setBackground(new java.awt.Color(255, 255, 255));
        toInput.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        toInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        toInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toInputActionPerformed(evt);
            }
        });

        costoEscasezInput.setEditable(false);
        costoEscasezInput.setBackground(new java.awt.Color(255, 255, 255));
        costoEscasezInput.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        costoEscasezInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        costoEscasezInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costoEscasezInputActionPerformed(evt);
            }
        });

        costoMantenimientoInput.setEditable(false);
        costoMantenimientoInput.setBackground(new java.awt.Color(255, 255, 255));
        costoMantenimientoInput.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        costoMantenimientoInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        costoMantenimientoInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costoMantenimientoInputActionPerformed(evt);
            }
        });

        TCUInput.setEditable(false);
        TCUInput.setBackground(new java.awt.Color(255, 255, 255));
        TCUInput.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        TCUInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TCUInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TCUInputActionPerformed(evt);
            }
        });

        nPedidosInput.setEditable(false);
        nPedidosInput.setBackground(new java.awt.Color(255, 255, 255));
        nPedidosInput.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        nPedidosInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nPedidosInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nPedidosInputActionPerformed(evt);
            }
        });

        reorderInput.setEditable(false);
        reorderInput.setBackground(new java.awt.Color(255, 255, 255));
        reorderInput.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        reorderInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        reorderInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reorderInputActionPerformed(evt);
            }
        });

        escasezMostrarLabel.setBackground(new java.awt.Color(255, 255, 255));
        escasezMostrarLabel.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        escasezMostrarLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        escasezMostrarLabel.setText("Costo de Escasez Unitaria:");
        escasezMostrarLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        escasezResult.setEditable(false);
        escasezResult.setBackground(new java.awt.Color(255, 255, 255));
        escasezResult.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        escasezResult.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        escasezResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escasezResultActionPerformed(evt);
            }
        });

        desviacionDemandaLabel.setBackground(new java.awt.Color(255, 255, 255));
        desviacionDemandaLabel.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        desviacionDemandaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        desviacionDemandaLabel.setText("desviación demanda");
        desviacionDemandaLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        desvDemandaInput.setEditable(false);
        desvDemandaInput.setBackground(new java.awt.Color(255, 255, 255));
        desvDemandaInput.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        desvDemandaInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        desvDemandaInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desvDemandaInputActionPerformed(evt);
            }
        });

        varianzaTimeLabel.setBackground(new java.awt.Color(255, 255, 255));
        varianzaTimeLabel.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        varianzaTimeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        varianzaTimeLabel.setText("varianza");
        varianzaTimeLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        varianzaTimeInput.setEditable(false);
        varianzaTimeInput.setBackground(new java.awt.Color(255, 255, 255));
        varianzaTimeInput.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        varianzaTimeInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        varianzaTimeInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varianzaTimeInputActionPerformed(evt);
            }
        });

        costoVentaLabel.setBackground(new java.awt.Color(255, 255, 255));
        costoVentaLabel.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        costoVentaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        costoVentaLabel.setText("Costo de Venta:");
        costoVentaLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        ventaInput.setEditable(false);
        ventaInput.setBackground(new java.awt.Color(255, 255, 255));
        ventaInput.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        ventaInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ventaInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventaInputActionPerformed(evt);
            }
        });

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Nivel de Seguridad");
        jLabel18.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        nivelSeguridadInput.setEditable(false);
        nivelSeguridadInput.setBackground(new java.awt.Color(255, 255, 255));
        nivelSeguridadInput.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        nivelSeguridadInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nivelSeguridadInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nivelSeguridadInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                    .addComponent(leadTimeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(mantenimientoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(escasezMostrarLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(varianzaTimeLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(costoVentaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(varianzaTimeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(escasezResult, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ventaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(desviacionDemandaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                    .addComponent(demandaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(costoInput)
                                    .addComponent(demandaInput)
                                    .addComponent(mantenimientoInput)
                                    .addComponent(leadTimeInput)
                                    .addComponent(adquisicionInput)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(desvDemandaInput))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(intervaloLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pedidosLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                .addComponent(EOQInput))
                            .addComponent(costoMantenimientoInput, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(toInput, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(costoEscasezInput, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nPedidosInput, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nivelSeguridadInput, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reorderInput, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TCUInput, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(demandaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(demandaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(EOQInput, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(desviacionDemandaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(desvDemandaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(intervaloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(toInput, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(costoInput, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nivelSeguridadInput, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mantenimientoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(mantenimientoInput, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(costoEscasezInput, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(leadTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(costoMantenimientoInput, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(leadTimeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(varianzaTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(varianzaTimeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pedidosLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nPedidosInput, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adquisicionInput, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TCUInput, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(escasezMostrarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(escasezResult, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reorderInput, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(costoVentaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ventaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(158, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void curvaButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_curvaButton2ActionPerformed

        GraphicCostos costosGrafica = new GraphicCostos(problema, unidad);
        costosGrafica.setVisible(true);
    }//GEN-LAST:event_curvaButton2ActionPerformed

    private void cierraButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cierraButton2ActionPerformed

        GraphicForm cierraGrafica = new GraphicForm(problema, unidad);
        cierraGrafica.setVisible(true);
    }//GEN-LAST:event_cierraButton2ActionPerformed

    private void demandaInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_demandaInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_demandaInputActionPerformed

    private void costoInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costoInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_costoInputActionPerformed

    private void mantenimientoInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mantenimientoInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mantenimientoInputActionPerformed

    private void leadTimeInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leadTimeInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leadTimeInputActionPerformed

    private void adquisicionInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adquisicionInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adquisicionInputActionPerformed

    private void EOQInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EOQInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EOQInputActionPerformed

    private void toInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toInputActionPerformed

    private void costoEscasezInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costoEscasezInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_costoEscasezInputActionPerformed

    private void costoMantenimientoInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costoMantenimientoInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_costoMantenimientoInputActionPerformed

    private void TCUInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TCUInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TCUInputActionPerformed

    private void nPedidosInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nPedidosInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nPedidosInputActionPerformed

    private void reorderInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reorderInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reorderInputActionPerformed

    private void escasezResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escasezResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_escasezResultActionPerformed

    private void desvDemandaInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desvDemandaInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desvDemandaInputActionPerformed

    private void varianzaTimeInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varianzaTimeInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_varianzaTimeInputActionPerformed

    private void ventaInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventaInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ventaInputActionPerformed

    private void nivelSeguridadInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nivelSeguridadInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nivelSeguridadInputActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EOQInput;
    private javax.swing.JTextField TCUInput;
    private javax.swing.JTextField adquisicionInput;
    private javax.swing.JButton cierraButton;
    private javax.swing.JButton cierraButton1;
    private javax.swing.JButton cierraButton2;
    private javax.swing.JTextField costoEscasezInput;
    private javax.swing.JTextField costoInput;
    private javax.swing.JTextField costoMantenimientoInput;
    private javax.swing.JLabel costoVentaLabel;
    private javax.swing.JButton curvaButton;
    private javax.swing.JButton curvaButton1;
    private javax.swing.JButton curvaButton2;
    private javax.swing.JTextField demandaInput;
    private javax.swing.JLabel demandaLabel;
    private javax.swing.JTextField desvDemandaInput;
    private javax.swing.JLabel desviacionDemandaLabel;
    private javax.swing.JLabel escasezMostrarLabel;
    private javax.swing.JTextField escasezResult;
    private javax.swing.JLabel intervaloLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField leadTimeInput;
    private javax.swing.JLabel leadTimeLabel;
    private javax.swing.JTextField mantenimientoInput;
    private javax.swing.JLabel mantenimientoLabel;
    private javax.swing.JTextField nPedidosInput;
    private javax.swing.JTextField nivelSeguridadInput;
    private javax.swing.JLabel pedidosLabel;
    private javax.swing.JTextField reorderInput;
    private javax.swing.JTextField toInput;
    private javax.swing.JTextField varianzaTimeInput;
    private javax.swing.JLabel varianzaTimeLabel;
    private javax.swing.JTextField ventaInput;
    // End of variables declaration//GEN-END:variables
    public Probabilistico problema;
    public String unidad;

    private void initLabel(String unidad) 
    {
        demandaLabel.setText("Media de la demanda en " + unidad+":");
        desviacionDemandaLabel.setText("Varianza de la demanda en " + unidad+":");
        mantenimientoLabel.setText("Costo de mantenimiento por " + unidad+":");
        leadTimeLabel.setText("Tiempo de espera en " + unidad+":");
        varianzaTimeLabel.setText("Varianza del tiempo de espera en " + unidad+":");
        intervaloLabel.setText("Intervalo de órdenes en "+ unidad+":");
        pedidosLabel.setText("Cantidad de pedidos en "+ unidad+":");    
    }
    
    private void initResultBasico(Probabilistico basico)
    {
        EOQInput.setText(Float.toString(basico.calcularCantidadOptimaOrdenar()));
        
        toInput.setText(Float.toString(basico.calcularTiempoEntreOrdenes()));
        
        double r = basico.calcularR();
        System.out.println("soy r en interfaz" + r);
        reorderInput.setText(String.format("%.2f", r));
        
        double seguridad = basico.calcularNivel_de_seguridad();
        nivelSeguridadInput.setText(String.format("%.2f", seguridad));
        
        
        TCUInput.setText(Float.toString(basico.calcularTCU()));
        
        costoEscasezInput.setText(Float.toString((float) basico.costo_escasez_anual()));
        
        costoMantenimientoInput.setText(Float.toString(basico.calcularCostoTotalMantenimiento()));
        
        
        
        nPedidosInput.setText(Float.toString(basico.calcularCantidadPedidosXTiempo()));
        
        demandaInput.setText(Float.toString(basico.getDemanda()));
        desvDemandaInput.setText(Float.toString(basico.getDesvDemanda())); 
        costoInput.setText(Float.toString(basico.getCosto_orden()));
        mantenimientoInput.setText(Float.toString(basico.getCosto_mantener()));
        leadTimeInput.setText(Float.toString(basico.getTiempo_carga()));
        varianzaTimeInput.setText(Float.toString(basico.getVarianzaL()));
        ventaInput.setText(Float.toString(basico.getCosto_venta()));
        escasezResult.setText(Float.toString(basico.getCostoUnitEscasez()));
        adquisicionInput.setText(Float.toString(basico.getCosto_adquisicion()));
          
    }



}
